### ISSUE TITLE
`scipy.stats.distributions` integration

### ISSUE THREAD

**Issue by jorenham** [jorenham/Lmo#10]
- [x] add methods `l_moment`, `l_stats`, etc.  to the "generic" and "frozen" distn bases (monkeypatch)
  -  [x] `rv_continuous` (depends #6), and use #5 + the `name` attribute to check if specific theoretical L-moments are known 
  - [x] `rv_discrete` (depends #9)
- [ ] for the theoretically-known distributions from #5, override `l_moment` on the specific `rv_continuous` instances
